server:
  port: 8001
spring:
  writedb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://yjhome.kro.kr:3306/user?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwer1234!
    hikari:
      maximum-pool-size: 10
  readdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://yjhome.kro.kr:3306/read?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwer1234!
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true
        show-sql: true
        generate-ddl: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://yjhome.kro.kr:10006/realms/KITe/protocol/openid-connect/certs

keycloak:
  realm: KITe
  resource: spring_auth
  auth-server-url: https://yjhome.kro.kr:10006
  bearer-only: true
  ssl-required: external
  credentials:
    secret: yt7mnKRgBWwwr8jYzoiaV0PHRm7hJWm0

logging:
  level:
   org:
     hibernate:
          type:
            descriptor:
              sql: trace  # query의 ?에 어떤 값이 들어가는지 TRACE Log에 값을 보여줌
